# Generated by Django 3.2.8 on 2021-11-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_diaria_data_atendimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaria',
            name='complemento',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
