# Generated by Django 3.2.8 on 2021-11-24 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0002_auto_20211021_1313'),
        ('api', '0010_auto_20211114_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaria',
            name='servico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administracao.servico'),
        ),
    ]
